  GNU nano 8.3                                                         compose.yml
services:
  nc:
    image: nextcloud:apache
    environment:
      - POSTGRES_HOST=aurora-postgres-dev.cluster-cw5ci80y8c8z.us-east-1.rds.amazonaws.com
      - POSTGRES_PASSWORD=MySecurePass123!
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=*
    ports:
      - 80:80
    restart: always
    volumes:
      - /mnt/efs/nextcloud:/var/www/html
    user: "33:33"
